[package]
name = "shopify_function_macro"
version = "0.1.0"
edition = "2021"
authors = ["Surma <surma@shopify.com>"]

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0.43"
