[package]
name = "shopify_rust_function"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shopify_rust_function_macro = {path = "../shopify_rust_function_macro"}
