[package]
name = "volume"
version = "1.0.0"
edition = "2021"

[dependencies]
shopify_rust_function = {path = "../shopify_rust_function"}
serde = { version = "1.0.13", features = ["derive"] }
serde_with = "1.13.0"
serde_json = "1.0"
