[package]
name = "shopify_function"
version = "0.2.3"
edition = "2021"
authors = ["Surma <surma@shopify.com>"]
license = "Apache-2.0"
description = "Crate to write Shopify Functions in Rust."

[dependencies]
serde = { version = "1.0.13", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.62"
shopify_function_macro = { version = "0.2.3", path = "../shopify_function_macro" }
