[package]
name = "shopify_function"
version = "0.1.0"
edition = "2021"
authors = ["Surma <surma@shopify.com>"]

[dependencies]
shopify_function_macro = {path = "../shopify_function_macro"}
serde = { version = "1.0.13", features = ["derive"] }
serde_with = "1.13.0"
serde_json = "1.0"
anyhow = "1.0.62"
